#pragma once

#include <lcom/lcf.h>

/* XPM */
static xpm_row_t const pawn[] = {
/* columns rows colors chars-per-pixel */
        "64 64 3",
        "  1",
        ". 2",
        "X 0",
/* pixels */
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

/* XPM */
static xpm_row_t const knight[] = {
/* columns rows colors chars-per-pixel */
        "64 64 3",
        "  1",
        ". 2",
        "X 0",
/* pixels */
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............            XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............            XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............            XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............            XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ....    ....................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ....    ....................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ....    ....................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ....    ....................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXX    ....................    ............    XXXXXXXXXXXX",
        "XXXXXXXX    ....................    ............    XXXXXXXXXXXX",
        "XXXXXXXX    ....................    ............    XXXXXXXXXXXX",
        "XXXXXXXX    ....................    ............    XXXXXXXXXXXX",
        "XXXXXXXX    ........            ................    XXXXXXXXXXXX",
        "XXXXXXXX    ........            ................    XXXXXXXXXXXX",
        "XXXXXXXX    ........            ................    XXXXXXXXXXXX",
        "XXXXXXXX    ........            ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX        XXXXXXXX    ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX        XXXXXXXX    ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX        XXXXXXXX    ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX        XXXXXXXX    ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ....................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

/* XPM */
static xpm_row_t const bishop[] = {
/* columns rows colors chars-per-pixel */
        "64 64 3",
        "  1",
        ". 2",
        "X 0",
/* pixels */
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ............XXXX    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ............XXXX    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ............XXXX    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ............XXXX    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............XXXX    ....    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............XXXX    ....    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............XXXX    ....    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............XXXX    ....    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............    ........    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............    ........    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............    ........    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ............    ........    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

/* XPM */
static xpm_row_t const rook[] = {
/* columns rows colors chars-per-pixel */
        "64 64 3",
        "  1",
        ". 2",
        "X 0",
/* pixels */
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXX            XXXX                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX            XXXX                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX            XXXX                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX            XXXX                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....    XXXX    ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....    XXXX    ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....    XXXX    ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....    XXXX    ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....            ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....            ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....            ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....            ................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXX    ................    XXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXX    ........................................    XXXXXXXX",
        "XXXXXXXX    ........................................    XXXXXXXX",
        "XXXXXXXX    ........................................    XXXXXXXX",
        "XXXXXXXX    ........................................    XXXXXXXX",
        "XXXXXXXX                                                XXXXXXXX",
        "XXXXXXXX                                                XXXXXXXX",
        "XXXXXXXX                                                XXXXXXXX",
        "XXXXXXXX                                                XXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

/* XPM */
static xpm_row_t const queen[] = {
/* columns rows colors chars-per-pixel */
        "64 64 3",
        "  1",
        ". 2",
        "X 0",
/* pixels */
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
        "XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
        "XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
        "XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
        "XXXXXXXX        XXXXXXXXXXXX        XXXXXXXXXXXX        XXXXXXXX",
        "XXXXXXXX        XXXXXXXXXXXX        XXXXXXXXXXXX        XXXXXXXX",
        "XXXXXXXX        XXXXXXXXXXXX        XXXXXXXXXXXX        XXXXXXXX",
        "XXXXXXXX        XXXXXXXXXXXX        XXXXXXXXXXXX        XXXXXXXX",
        "XXXXXXXX    ....    XXXX    ........    XXXX    ....    XXXXXXXX",
        "XXXXXXXX    ....    XXXX    ........    XXXX    ....    XXXXXXXX",
        "XXXXXXXX    ....    XXXX    ........    XXXX    ....    XXXXXXXX",
        "XXXXXXXX    ....    XXXX    ........    XXXX    ....    XXXXXXXX",
        "XXXXXXXX    ........    ................    ........    XXXXXXXX",
        "XXXXXXXX    ........    ................    ........    XXXXXXXX",
        "XXXXXXXX    ........    ................    ........    XXXXXXXX",
        "XXXXXXXX    ........    ................    ........    XXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

/* XPM */
static xpm_row_t const king[] = {
/* columns rows colors chars-per-pixel */
        "64 64 3",
        "  1",
        ". 2",
        "X 0",
/* pixels */
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXX    ........    XXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXX            XXXX        XXXX            XXXXXXXXXXXX",
        "XXXXXXXXXXXX            XXXX        XXXX            XXXXXXXXXXXX",
        "XXXXXXXXXXXX            XXXX        XXXX            XXXXXXXXXXXX",
        "XXXXXXXXXXXX            XXXX        XXXX            XXXXXXXXXXXX",
        "XXXXXXXX    ............    XXXXXXXX    ............    XXXXXXXX",
        "XXXXXXXX    ............    XXXXXXXX    ............    XXXXXXXX",
        "XXXXXXXX    ............    XXXXXXXX    ............    XXXXXXXX",
        "XXXXXXXX    ............    XXXXXXXX    ............    XXXXXXXX",
        "XXXXXXXX    ....XXXX    ....        ....    XXXX....    XXXXXXXX",
        "XXXXXXXX    ....XXXX    ....        ....    XXXX....    XXXXXXXX",
        "XXXXXXXX    ....XXXX    ....        ....    XXXX....    XXXXXXXX",
        "XXXXXXXX    ....XXXX    ....        ....    XXXX....    XXXXXXXX",
        "XXXXXXXX    ....XXXXXXXX    ........    XXXXXXXX....    XXXXXXXX",
        "XXXXXXXX    ....XXXXXXXX    ........    XXXXXXXX....    XXXXXXXX",
        "XXXXXXXX    ....XXXXXXXX    ........    XXXXXXXX....    XXXXXXXX",
        "XXXXXXXX    ....XXXXXXXX    ........    XXXXXXXX....    XXXXXXXX",
        "XXXXXXXX    ....    XXXXXXXX........XXXXXXXX    ....    XXXXXXXX",
        "XXXXXXXX    ....    XXXXXXXX........XXXXXXXX    ....    XXXXXXXX",
        "XXXXXXXX    ....    XXXXXXXX........XXXXXXXX    ....    XXXXXXXX",
        "XXXXXXXX    ....    XXXXXXXX........XXXXXXXX    ....    XXXXXXXX",
        "XXXXXXXXXXXX    ....        ........        ....    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....        ........        ....    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....        ........        ....    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ....        ........        ....    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX    ........................    XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX    ................................    XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXX                                        XXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};
